// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvHgV1ssFjem3YqAa46oiZ4ZJ-q_7F8Ak',
    appId: '1:697586260535:android:2536a7161c3b297e4c7db2',
    messagingSenderId: '697586260535',
    projectId: 'flutter-shop-app-365508',
    databaseURL: 'https://flutter-shop-app-365508-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-shop-app-365508.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPhJpuWyjYp_ZGSqxSLCtaH5s3Y979V20',
    appId: '1:697586260535:ios:1bd37790f758a7824c7db2',
    messagingSenderId: '697586260535',
    projectId: 'flutter-shop-app-365508',
    databaseURL: 'https://flutter-shop-app-365508-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-shop-app-365508.appspot.com',
    iosClientId: '697586260535-uut5kul0s6cnqsa28pisunlms4rfn2tq.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );
}
